### ISSUE TITLE
restructure /admincards into /persons-of-note

### ISSUE THREAD

**Issue by jakubmanczak** [gractwo/api#3]
In order to support returning cards and profiles of those outside of the administrative group, it would be wise to alter this endpoint accordingly:

* change its name from `/admincards` to `persons-of-note`

* alter its returning json by adding the `isAdmin` boolean field, thus keeping the old `/admincards` functionality where needed

```ts
[
  {
    "Id": string;             // ID
    "Name": string;           // user name
    "Desc": string;           // user description (short)
    "Img": string;            // direct url to an image
    "IsAdmin": bool;          // whether user is part of the admin team
    "DevBadge": bool;         // whether user should have a dev badge visible
    "AssignedUser": string;   // discord snowflake
  }, {...}
]
```

This would obviously require further changes in both _the database_ and the _web frontend_, disabling parts of [gractwo.pl](https://gractwo.pl)'s functionality until completed.

This change has already been reflected in the [api docs](https://github.com/gractwo/api/wiki#recent-changes).

It would also be wise to start thinking about the solution to handling the profile data of each user in addition to the card data - perhaps as a child array in the same response?

**Comment by BoberITman** [comment]
Resolved
